### ISSUE TITLE
Ability to comment and add attachments to an existing JIRA

### ISSUE THREAD

**Issue by febinrejoe** [danrspencer/jira-resource#12]
I have an use case for adding comments (like smart commits) and attachments (test evidence) to a JIRA story from our Concourse build pipeline. Do you mind if I add that functionality to your resource?

I thought of creating a new resource, but it makes more sense to add it to ```jira-resource```. Please let me know your thoughts. If you are okay, I can create a PR.

**Comment by danrspencer** [comment]
Yep, I'd be happy to merge a pull request if you want to create one 👍

**Comment by SimonXming** [comment]
#15 support for add comments.
