### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by AdeOpe** [danrspencer/jira-resource#16]
Hi
The readme says

-   `transitions`: An array of string values for the ticket to be moved though.

but it should say
-   `transitions`: An array of string values for the ticket to be moved through.

FYI - I tried to push a bugfix branch to remote, but i don't have permission
![image](https://user-images.githubusercontent.com/5416277/53226654-a6dab200-3673-11e9-8a7c-c5e1e1fb1364.png)

thanks

**Comment by danrspencer** [comment]
Cheers, I changed it 👍
