### ISSUE TITLE
Infinite Loop when Git Permission Denied

### ISSUE THREAD

**Issue by gowrisankar22** [danrspencer/jira-resource#2]
Hi ,

I am getting below error, yml file looks like below for semver resource.

 - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:danrspencer/jira-resource.git
      branch: version
      private_key: ((private-repo-key))
      file: version

Cloning into '/tmp/semver-git-repo'...
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
HEAD is now at e8ed0ce bump to 0.2.16
ERROR: Permission to danrspencer/jira-resource.git denied to gowrisankar22.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
From github.com:danrspencer/jira-resource
 * branch            version    -> FETCH_HEAD
HEAD is now at e8ed0ce bump to 0.2.16
ERROR: Permission to danrspencer/jira-resource.git denied to gowrisankar22.
fatal: Could not read from remote repository.

Can you check what is wrong here?

**Comment by danrspencer** [comment]
Hi,

I'm not actively maintaining this repo at the moment. Feel free to sent a pull request though.

Cheers,
