### ISSUE TITLE
Update a ticket using the ID

### ISSUE THREAD

**Issue by kalfa** [danrspencer/jira-resource#7]
It seems that a ticket can be updated only if its summary matches.

What about allowing a ticket to be updated if matches a given id?

Id can be in the form of <project>-<id>, e.g. PROJ-10
or just <id>, e.g. 10, meaning actually PROJ-10, where PROJ is the project configured for the resource

The idea is to update a ticket with the build result in its comments.

**Comment by danrspencer** [comment]
Hi, 

I'm not actively maintain this repo, however I'm happy to merge in any changes if you want to submit a pull request.

Cheers,

**Comment by kalfa** [comment]
OK, thanks

Could you drop a note in the README.md about the repo being not actively maintained, please?
I think this is an important info for whoever stumbles upon it.
